#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir 0

./prepareCase.sh

# Set application name
application="waveFoam"

# Create the computational mesh
runApplication blockMesh

# Compute the wave parameters
runApplication setWaveParameters

# Set the wave field
runApplication setWaveField

# Create the wave probes
runApplication waveGaugesNProbes

# Run the application
runApplication $application

# To a post-processing analysis
runApplication postProcessWaves2Foam
